# Generated by Django 3.2.15 on 2022-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20220829_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DE', 'Delivered'), ('ND', 'Notdelivered'), ('OP', 'Onprocess'), ('VF', 'Verified'), ('NV', 'Notverified')], default='OP', max_length=2),
        ),
    ]
