# Generated by Django 3.2.15 on 2022-08-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Ref_No',
        ),
    ]
